### ISSUE TITLE
Stage add and Remove is not working Properly

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#24]
When we add  multiple stages at one time and then delete from between, and submit. Then when we come to Job Vacancy page all Stages are Coming and makes duplicate entries on DB.

http://beta.talentify.in:8121/recruiter/jobs.jsp

![image](https://cloud.githubusercontent.com/assets/16954148/20423226/2e7064fe-ad95-11e6-874b-68de14074a18.png)

**Comment by mayank-istar** [comment]
irelevent now
