### ISSUE TITLE
reset password error

### ISSUE THREAD

**Issue by akshayISTAR** [ISTARSkills/istarissues#312]
on reseting the password, the password is updated in the database, but it is showing error text and not going to the login activity and error text does not hide on focus on edittext

**Comment by akshayISTAR** [comment]
implement onclick listener on sign in with different account and back handling

**Comment by akshayISTAR** [comment]
implement validation of password length

**Comment by ajithkpistar** [comment]
take a pull and retest

**Comment by akshayISTAR** [comment]
tested ok
