### ISSUE TITLE
Course Dashboard - showing Category Name - null. And Content in card are not aligned || Module || Session

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#317]
![image](https://cloud.githubusercontent.com/assets/16954148/25699080/5a275dc8-30df-11e7-87e7-2edd62b87e29.png)

**Comment by absin1** [comment]
There are 2 ways of solving this problem, either I include a validation on the course image not being null or I insert a dummy image in the course list page whenever there is no image in the course. 
IMHO I will go ahead with validation of the form, as its a fool proof solution.
Clubbing this with issue 322

**Comment by absin1** [comment]
New ui has category input, also image input has a default so this problem wont happen
