### ISSUE TITLE
 Skill Administration >> Skill Tasks >> edit skill tree -  Text content is going  out of the box .

### ISSUE THREAD

**Issue by shivu-L** [ISTARSkills/istarissues#319]
http://192.168.0.106:8080/content/content_creator/edit_skill_tree.jsp?skill_id=1&task_id=32155

![image](https://cloud.githubusercontent.com/assets/28298731/25699729/131a8114-30e2-11e7-90bd-37901d674f27.png)

**Comment by absin1** [comment]
I am thinking of changing the plugin, as I cannot get it to do some fundamental jobs for me. Will revert on this thread post that.

**Comment by absin1** [comment]
UI changed take pull and check if the issue persists
