### ISSUE TITLE
Showing no image while creating module (Default creation, without uploading image) || Session

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#322]
![image](https://cloud.githubusercontent.com/assets/16954148/25701057/3aae8648-30e8-11e7-9088-bf8001a2ed58.png)

**Comment by absin1** [comment]
Do you mean there should be a validation on form to prevent image-less module creation?

**Comment by vinayistar** [comment]
It showing some image, which should not be shown till we upload

**Comment by absin1** [comment]
New UI has a dummy image, if none used the same url gets saved.
