### ISSUE TITLE
Lesson video - mp4 videos not able to upload

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#335]
http://192.168.0.106:8080/content/content_creator/edit_video_lesson.jsp?lesson_id=40

![image](https://cloud.githubusercontent.com/assets/16954148/25705793/25d5f666-30fc-11e7-999f-b0564edf55e8.png)

**Comment by absin1** [comment]
Can do now, check again

**Comment by shivu-L** [comment]
Uploaded video and Thumbnails are not visible in lesson.

http://192.168.0.106:8080/content/content_creator/edit_lesson.jsp?lesson_id=4
