### ISSUE TITLE
Issue with Edit trainer info. Unable to get mail after changing Password and other fields are also not updated @android side

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#35]
1. When i change Password of any particular user, then that user should get mail or notification.
2. If i change any field like mobile no. or name then that should be visible in android app also.

http://beta.talentify.in:8121/orgadmin/trainer/edit_trainerlist.jsp?trainer_id=449

**Comment by ravybathla** [comment]
Resolved for #1.

**Comment by ravybathla** [comment]
Resolved for #2

**Comment by vinayistar** [comment]
Resolved
