### ISSUE TITLE
nothing is updated in account settings in my profile

### ISSUE THREAD

**Issue by akshayISTAR** [ISTARSkills/istarissues#362]
error message in mobile no. edit text shadows the tick mark and spelling of 'receive' is wrong

**Comment by Feroz-Istar** [comment]
fixed take a pull. puttingit in retesting

**Comment by akshayISTAR** [comment]
data is getting saved only when we go to another activity

**Comment by akshayISTAR** [comment]
in account setting tab , the profile info is getting saved but on going to another activity, but the professional qualification is not getting saved in the database.

**Comment by akshayISTAR** [comment]
error message in mobile no. edit text shadows the tick mark is still pending

**Comment by akshayISTAR** [comment]
tested ok
