### ISSUE TITLE
Question - Unable to edit question. (Update option or any field is not updating)

### ISSUE THREAD

**Issue by akshayISTAR** [ISTARSkills/istarissues#390]
I want to edit question urgently to update skills of question and to see the result in app side
By Vinay

**Comment by vinayistar** [comment]
![image](https://cloud.githubusercontent.com/assets/16954148/25860717/12951516-3500-11e7-85f4-accf0bd4bec8.png)

In this ui some issues are thr like
1) If i chose a context then i will be bound to select skill and learning objective under that context only. 
This leads to difficulty in creating same question under any other context.

**Comment by absin1** [comment]
Added a separate dropdown just for choosing the context, the 3 drop downs for choosing lo are now separate from the context of the question. So the question can belong to one context and can also have learning objectives corresponding to a different context.
