### ISSUE TITLE
Student name is not reflected in web app

### ISSUE THREAD

**Issue by divith-istar** [ISTARSkills/istarissues#40]
if student is sign in with google, in dash board student name is not reflecting shows "NOT_PROVIDED", even in db and org_admin also same problem when accessing the student profile.

![image](https://cloud.githubusercontent.com/assets/20471874/20552940/e6ea3c42-b175-11e6-8962-f9fd063b96df.png)

**Comment by ravybathla** [comment]
resolved from OrgAdmin!
