### ISSUE TITLE
Batch Dashboard - In Attendance table there is no clue of Trainer assigned to that event date and also in Printout No trainer name available

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#43]
There should be trainer name column that shows which trainer is assigned to that event time.(Unknown trainer Name) And also if Detail is Print option then in printout there should be Trainer name present below batch name

![image](https://cloud.githubusercontent.com/assets/16954148/20556914/34faa5d4-b18f-11e6-9413-bc1c57b9044e.png)

**Comment by ravybathla** [comment]
resolved

**Comment by vinayistar** [comment]
Tested
