### ISSUE TITLE
In Batch Group of any Organization, Onclick of Trainer Image icon, shows 404 error Page 

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#44]
When we go to Batch group of particular Organization dashboard, and click on Trainer image icon shows 404 error page.

http://admin.talentify.in:8080/orgadmin/batch_group/dashboard.jsp?batch_group_id=123

![image](https://cloud.githubusercontent.com/assets/16954148/20562705/06b7c168-b1ab-11e6-86d9-50f33c55b872.png)

**Comment by ravybathla** [comment]
resolved!

**Comment by vinayistar** [comment]
tested
