### ISSUE TITLE
While creating a group if i use special character as a group name, group search drop down not works properly.

### ISSUE THREAD

**Issue by Ravichandratech** [ISTARSkills/istarissues#602]
In console throwing error like "Error: Syntax error, unrecognized expression: .Minions///" and searching different groups and .
![untitled](https://user-images.githubusercontent.com/28383663/34718549-0ca34236-f55d-11e7-9333-e8857df9ddc1.png)

**Comment by JithendarM** [comment]
Checked

**Comment by Ravichandratech** [comment]
If i copy paste it is not working.

**Comment by JithendarM** [comment]
checked
