### ISSUE TITLE
Same option multiple times available and also single option available in a question

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#78]
Assessment_id =10244 Careerprep verbal reasoning session_id-922

![screenshot_20170104-141056 1](https://cloud.githubusercontent.com/assets/16954148/21671880/88bdb7b6-d344-11e6-8d1e-0f126dda6c97.png)

Single Option available in Number Theory Basics.
Assessment id= 10238

![screenshot_20170105-132128 1](https://cloud.githubusercontent.com/assets/16954148/21672681/085e1ed4-d34a-11e6-89cb-d4b913810cbb.png)

![screenshot_20170105-132135 1]
(https://cloud.githubusercontent.com/assets/16954148/21672686/0fe263b8-d34a-11e6-9070-2b3c46fa1014.png)

There is issue with question text:-
Assessment_id = 10014
![screenshot_20170104-164731 1](https://cloud.githubusercontent.com/assets/16954148/21672304/b182e63c-d347-11e6-9ac9-9368ec14ab6d.png)

**Comment by ajithkpistar** [comment]
Content Issue

**Comment by vinayistar** [comment]
Partially fixed and some of them assigned to content
