### ISSUE TITLE
Unable to predict the download state and UI of searching Sessions is not appropriate

### ISSUE THREAD

**Issue by vinayistar** [ISTARSkills/istarissues#79]
When we start download the course, and remain in Learn section, we cant get to know that the course is downloaded since the icon is not changing immediately the course is downoaded.

When we search a session and there are multiple result in some course that is downloaded, then the UI is not appropriate since it shows downloaded only in the first Session. It should show in all downloaded sessions in that course
![screenshot_20170105-133221 1](https://cloud.githubusercontent.com/assets/16954148/21672995/337c61aa-d34c-11e6-9f2f-0ea374464390.png)

**Comment by ajithkpistar** [comment]
Fixed,Retest please

**Comment by vinayistar** [comment]
Tested
