### ISSUE TITLE
Assessment question_text(passage) having white background

### ISSUE THREAD

**Issue by karthik-istar** [ISTARSkills/istarissues#83]
Course : carreprep logical reasoning 

assessment id : 10300

assessment name : syllogism_post assessment

![screenshot_2017-01-05-15-32-50](https://cloud.githubusercontent.com/assets/21259158/21677245/66ec2274-d35f-11e6-917b-4f2fe8e95739.png)

**Comment by ajithkpistar** [comment]
Re assign to Content
