### ISSUE TITLE
Issues in Carreprep GD/PI course

### ISSUE THREAD

**Issue by karthik-istar** [ISTARSkills/istarissues#85]
After downloading the entire course these are all the issues we faced.

Issue           :   Video is playing
Course        : carrerprep GD/PI
session       : Technology in business communication 
PPT ID        : 128
Lession ID  : 961

Issue           :  Backgroung image is not visible. Accessability is to low.
Course        : carrerprep GD/PI
session       : Digital marketing 
PPT ID        : 667
Lession ID  : 6082

Issue           :  Special charecter
Course        : carrerprep GD/PI
session       : Making personality based career choices
PPT ID        : 760
Lession ID  : 5710

![screenshot_2017-01-05-18-58-01](https://cloud.githubusercontent.com/assets/21259158/21682554/40819e04-d37b-11e6-8624-7e4cd461c5ef.png)

**Comment by ajithkpistar** [comment]
Retest pls
