### ISSUE TITLE
Multiple time sessions are appearing in the search window.

### ISSUE THREAD

**Issue by karthik-istar** [ISTARSkills/istarissues#90]
If we look for a specific course in a search window it appears multiple time.

![screenshot_2017-01-10-16-01-59](https://cloud.githubusercontent.com/assets/21259158/21803115/9fe68f54-d74e-11e6-901e-9e3380d26133.png)

**Comment by ajithkpistar** [comment]
Fixed Retest Pls

**Comment by vinayistar** [comment]
Retested
